server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgres://localhost:5432/academia
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace